# LOGISTIC REGRESSION

In [34]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#%matplotlib in line 


In [35]:
from sklearn.datasets import make_classification 

In [36]:
""""
Create a dataset
n_classes = number of classes
n_features = number of features
n_samples = number of samples
"""

X, Y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state =42)


Convert X to dataframe

In [37]:
pd.DataFrame(X).head()

0         1         2         3         4         5         6  \
0  0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1 -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2 -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3  1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4 -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   

          7         8         9  
0 -1.210161 -0.628077  1.227274  
1 -0.984534  0.363896  0.209470  
2 -0.246383 -1.058145 -0.297376  
3 -0.357445 -1.473127 -0.190039  
4 -0.939156  0.175915  0.236224

### Train Test Split

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, random_state = 42)

### Model Training - Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression
logisticRegression = LogisticRegression ()


In [40]:
# Train Model
logisticRegression.fit(X_train, Y_train)


LogisticRegression()

In [41]:
# Predictions
Y_pred = logisticRegression.predict(X_test)
print(Y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1]


In [42]:
# Predicition Probabilites of the classes

#LogisticRegression.predict_proba(X_test)


### Performance Metrices

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 

In [44]:
score = accuracy_score(Y_test, Y_pred)
print(f"Accuracy = {score}")

Accuracy = 0.83


In [45]:
_confusion_matrix = confusion_matrix(Y_test, Y_pred)
print(_confusion_matrix)



[[75 14]
 [20 91]]


In [46]:
_classification_report = classification_report(Y_test, Y_pred)
print(_classification_report)

              precision    recall  f1-score   support

           0       0.79      0.84      0.82        89
           1       0.87      0.82      0.84       111

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200



# HYPERPARAMETER TUNING

In [67]:
model=LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
C=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [68]:
hyper_parameters = dict(penalty = penalty, solver = solver, C = C)


#params=dict(penalty=penalty,C=c_values,solver=solver)

### Grid Search CV

In [69]:
# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import StratifiedKFold
# cv = StratifiedKFold()


from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [70]:
#grid = GridSearchCV(estimator = model, param_grid = hyper_parameters, cv = cv, scoring = 'accuracy', n_jobs = -1)


## GridSearchCV
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=model,param_grid=hyper_parameters, scoring='accuracy',cv=cv,n_jobs=-1)

In [71]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [72]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')


In [79]:
#grid.fit(X_train, Y_train)


In [80]:
# Best Paramters selected by GridSearchCV
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}

In [81]:
grid.best_score_

0.8787500000000001

In [82]:
### Performance Metrices
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
score = accuracy_score(Y_test, Y_pred)
print(f"Accuracy = {score}")
_confusion_matrix = confusion_matrix(Y_test, Y_pred)
print(_confusion_matrix)


_classification_report = classification_report(Y_test, Y_pred)
print(_classification_report)

Accuracy = 0.83
[[75 14]
 [20 91]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82        89
           1       0.87      0.82      0.84       111

    accuracy                           0.83       200
   macro avg       0.83      0.83      0.83       200
weighted avg       0.83      0.83      0.83       200



# RANDOMIZED SEARCH CV

In [83]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
random_cv = RandomizedSearchCV(estimator = model, param_distributions=hyper_parameters, cv=5, scoring = 'accuracy')


In [100]:
#random_cv.fit(X_train,Y_train)

In [86]:
random_cv.best_score_

0.8787499999999999

In [85]:
random_cv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.01}

In [87]:
Y_pred = random_cv.predict(X_test)

In [88]:
### Performance Metrices
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
score = accuracy_score(Y_test, Y_pred)
print(f"Accuracy = {score}")
_confusion_matrix = confusion_matrix(Y_test, Y_pred)
print(_confusion_matrix)


_classification_report = classification_report(Y_test, Y_pred)
print(_classification_report)

Accuracy = 0.825
[[78 11]
 [24 87]]
              precision    recall  f1-score   support

           0       0.76      0.88      0.82        89
           1       0.89      0.78      0.83       111

    accuracy                           0.82       200
   macro avg       0.83      0.83      0.82       200
weighted avg       0.83      0.82      0.83       200



# Logistic Regression For Multiclass Classification Problem

In [91]:
""""
Create a dataset
n_classes = number of classes
n_features = number of features
n_samples = number of samples
n_informative = number of informative features
"""

X, Y = make_classification(n_informative=3, n_samples=1000, n_features=10, n_classes=3, random_state =42)

In [94]:
### Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, random_state = 42)


In [95]:
### Model Training - Logistic Regression
from sklearn.linear_model import LogisticRegression
logisticRegression = LogisticRegression (multi_class='ovr')


In [ ]:

# Train Model
logisticRegression.fit(X_train, Y_train)


In [98]:

# Predictions
Y_pred = logisticRegression.predict(X_test)
print(Y_pred)


[2 0 1 2 0 1 2 0 0 2 2 2 2 2 2 2 2 1 0 0 0 0 2 0 1 0 2 1 0 2 2 0 1 0 0 2 2
 2 1 0 0 1 2 0 1 2 1 0 1 1 2 0 1 0 2 2 2 2 1 2 0 2 2 2 1 1 0 1 0 1 0 2 2 0
 0 0 2 1 1 2 2 0 2 1 0 1 1 2 1 1 2 2 0 2 2 2 1 0 0 0 0 2 1 0 2 0 1 0 0 2 0
 1 2 0 0 0 1 1 2 2 1 0 0 1 2 0 0 1 0 2 1 0 2 2 2 0 0 1 2 1 2 1 2 1 2 2 2 0
 0 1 2 0 0 2 1 0 0 0 2 0 0 0 2 2 2 2 2 0 2 0 0 2 1 0 0 0 1 1 1 2 2 0 0 2 0
 0 0 2 0 0 0 0 2 1 2 2 1 2 0 1]


In [99]:
# Predicition Probabilites of the classes

#LogisticRegression.predict_proba(X_test)

### Performance Metrices
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
score = accuracy_score(Y_test, Y_pred)
print(f"Accuracy = {score}")
_confusion_matrix = confusion_matrix(Y_test, Y_pred)
print(_confusion_matrix)


_classification_report = classification_report(Y_test, Y_pred)
print(_classification_report)

Accuracy = 0.65
[[49 12  5]
 [25 27 17]
 [ 2  9 54]]
              precision    recall  f1-score   support

           0       0.64      0.74      0.69        66
           1       0.56      0.39      0.46        69
           2       0.71      0.83      0.77        65

    accuracy                           0.65       200
   macro avg       0.64      0.65      0.64       200
weighted avg       0.64      0.65      0.64       200

